/*
    This file is part of VK/KittenPHP-DB-Engine.

    VK/KittenPHP-DB-Engine is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    VK/KittenPHP-DB-Engine is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VK/KittenPHP-DB-Engine.  If not, see <http://www.gnu.org/licenses/>.

    This program is released under the GPL with the additional exemption
    that compiling, linking, and/or using OpenSSL is allowed.
    You are free to remove this exemption from derived works.

    Copyright 2011-2013 Vkontakte Ltd
              2011-2013 Anton Maydell
*/

/* Generated by python script */
#include <stdio.h>
#include <assert.h>
#include "copyexec-err.h"
char *copyexec_strerror (int err) {
  static char buf[64];  switch (err) {
    case COPYEXEC_ERR_LSEEK: return "COPYEXEC_ERR_LSEEK"; break;
    case COPYEXEC_ERR_READ: return "COPYEXEC_ERR_READ"; break;
    case COPYEXEC_ERR_CRC32: return "COPYEXEC_ERR_CRC32"; break;
    case COPYEXEC_ERR_TYPE: return "COPYEXEC_ERR_TYPE"; break;
    case COPYEXEC_ERR_DECRYPT: return "COPYEXEC_ERR_DECRYPT"; break;
    case COPYEXEC_ERR_MALLOC: return "COPYEXEC_ERR_MALLOC"; break;
    case COPYEXEC_ERR_ALIGN: return "COPYEXEC_ERR_ALIGN"; break;
    case COPYEXEC_ERR_SIZE: return "COPYEXEC_ERR_SIZE"; break;
    case COPYEXEC_ERR_SHA1: return "COPYEXEC_ERR_SHA1"; break;
    case COPYEXEC_ERR_MKDIR: return "COPYEXEC_ERR_MKDIR"; break;
    case COPYEXEC_ERR_OPEN: return "COPYEXEC_ERR_OPEN"; break;
    case COPYEXEC_ERR_FSTAT: return "COPYEXEC_ERR_FSTAT"; break;
    case COPYEXEC_ERR_ST_DEV: return "COPYEXEC_ERR_ST_DEV"; break;
    case COPYEXEC_ERR_ST_INO: return "COPYEXEC_ERR_ST_INO"; break;
    case COPYEXEC_ERR_READIN: return "COPYEXEC_ERR_READIN"; break;
    case COPYEXEC_ERR_STATUS: return "COPYEXEC_ERR_STATUS"; break;
    case COPYEXEC_ERR_FORK: return "COPYEXEC_ERR_FORK"; break;
    case COPYEXEC_ERR_CHDIR: return "COPYEXEC_ERR_CHDIR"; break;
    case COPYEXEC_ERR_CREAT: return "COPYEXEC_ERR_CREAT"; break;
    case COPYEXEC_ERR_STAT: return "COPYEXEC_ERR_STAT"; break;
    case COPYEXEC_ERR_PUBKEY_PERMISSIONS: return "COPYEXEC_ERR_PUBKEY_PERMISSIONS"; break;
    case COPYEXEC_ERR_INVAL: return "COPYEXEC_ERR_INVAL"; break;
    case COPYEXEC_ERR_VOLUME_ID_MISMATCHED: return "COPYEXEC_ERR_VOLUME_ID_MISMATCHED"; break;
    case COPYEXEC_ERR_HOSTNAME_MISMATCHED: return "COPYEXEC_ERR_HOSTNAME_MISMATCHED"; break;
    case COPYEXEC_ERR_DISCONNECT: return "COPYEXEC_ERR_DISCONNECT"; break;
    case COPYEXEC_ERR_OLD_RESULT: return "COPYEXEC_ERR_OLD_RESULT"; break;
    case COPYEXEC_ERR_UNKNOWN: return "COPYEXEC_ERR_UNKNOWN"; break;
    default: assert (snprintf (buf, sizeof (buf), "COPYEXEC_ERR_UNKNOWN (%d)", err) < sizeof (buf));
             return buf;
  }
}
