/*
    This file is part of VK/KittenPHP-DB-Engine.

    VK/KittenPHP-DB-Engine is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    VK/KittenPHP-DB-Engine is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VK/KittenPHP-DB-Engine.  If not, see <http://www.gnu.org/licenses/>.

    This program is released under the GPL with the additional exemption
    that compiling, linking, and/or using OpenSSL is allowed.
    You are free to remove this exemption from derived works.

    Copyright 2011-2013 Vkontakte Ltd
              2011-2013 Anton Maydell
*/

/* Generated by python script */
#define COPYEXEC_ERR_LSEEK (-1)
#define COPYEXEC_ERR_READ (-2)
#define COPYEXEC_ERR_CRC32 (-3)
#define COPYEXEC_ERR_TYPE (-4)
#define COPYEXEC_ERR_DECRYPT (-5)
#define COPYEXEC_ERR_MALLOC (-6)
#define COPYEXEC_ERR_ALIGN (-7)
#define COPYEXEC_ERR_SIZE (-8)
#define COPYEXEC_ERR_SHA1 (-9)
#define COPYEXEC_ERR_MKDIR (-10)
#define COPYEXEC_ERR_OPEN (-11)
#define COPYEXEC_ERR_FSTAT (-12)
#define COPYEXEC_ERR_ST_DEV (-13)
#define COPYEXEC_ERR_ST_INO (-14)
#define COPYEXEC_ERR_READIN (-15)
#define COPYEXEC_ERR_STATUS (-16)
#define COPYEXEC_ERR_FORK (-17)
#define COPYEXEC_ERR_CHDIR (-18)
#define COPYEXEC_ERR_CREAT (-19)
#define COPYEXEC_ERR_STAT (-20)
#define COPYEXEC_ERR_PUBKEY_PERMISSIONS (-21)
#define COPYEXEC_ERR_INVAL (-22)
#define COPYEXEC_ERR_VOLUME_ID_MISMATCHED (-23)
#define COPYEXEC_ERR_HOSTNAME_MISMATCHED (-24)
#define COPYEXEC_ERR_DISCONNECT (-25)
#define COPYEXEC_ERR_OLD_RESULT (-26)
#define COPYEXEC_ERR_UNKNOWN (-999)
char *copyexec_strerror (int err);
